# Generated by Django 5.1.1 on 2024-10-15 13:50

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagForProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('mini_description', models.CharField(default='', max_length=300)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2024, 10, 15, 18, 50, 21, 482594))),
                ('imageField', models.ImageField(default='projects/projects_pics/default.png', null=True, upload_to='projects/projects_pics')),
                ('viewsCount', models.IntegerField(default=0)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='projects', to='projects.hashtagforproject')),
            ],
        ),
    ]
