# Generated by Django 5.1.1 on 2024-09-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('imageField', models.ImageField(default=None, upload_to='blogs_pics/')),
                ('viewsCount', models.IntegerField(default=0)),
                ('hashtags', models.ManyToManyField(blank=True, related_name='posts', to='blogs.hashtag')),
            ],
        ),
    ]
