# Generated by Django 5.1.1 on 2024-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hashTag',
        ),
        migrations.AddField(
            model_name='blog',
            name='hashTags',
            field=models.ManyToManyField(blank=True, to='blogs.hashtag'),
        ),
    ]
