# Generated by Django 5.1.1 on 2024-09-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_hashtag_blog_hashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='hashTags',
            new_name='hashtags',
        ),
    ]
