# Generated by Django 5.1.1 on 2024-09-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_hashtags_blog_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blogs.hashtag'),
        ),
    ]
