# Generated by Django 5.1.1 on 2024-10-02 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_slug_alter_blog_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 10, 24, 11, 947796)),
        ),
    ]
