# Generated by Django 5.1.1 on 2024-10-05 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_datecreated_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mini_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 10, 33, 1, 194974)),
        ),
    ]
