# Generated by Django 5.1.1 on 2024-10-05 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_mini_description_alter_blog_datecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imageField',
        ),
        migrations.AlterField(
            model_name='blog',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 10, 35, 18, 33256)),
        ),
    ]
