# Generated by Django 5.1.1 on 2024-10-05 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_remove_blog_imagefield_alter_blog_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageField',
            field=models.ImageField(default=None, upload_to='blogs/blogs_pics'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 10, 38, 18, 234953)),
        ),
    ]
