# Generated by Django 5.1.1 on 2024-10-15 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_alter_blog_datecreated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtag',
            new_name='HashtagForBlog',
        ),
        migrations.AlterField(
            model_name='blog',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 18, 50, 21, 480551)),
        ),
    ]
